# Generated by Django 5.1.7 on 2025-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_profile_frame_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
