version: "3.9"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./.env:/app/.env  
    ports:
      - "8000:8000"
    env_file:
      - .env 
    depends_on:
      - mailhog
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    command: npm run dev  
    ports:
      - "3000:3000"
    depends_on:
      - django
    volumes:
      - ./frontend:/app
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .nuxt/
            - dist/

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: audio-files
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data

volumes:
  minio-data: