[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    migrations
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["backend"]
line_length = 88

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "project.settings"
