[tool.black]
line-length = 88
target-version = ['py313']
exclude = '''
/(
    migrations
  | venv
  | \.env
  | build
  | dist
  | manage\.py
<<<<<<< Updated upstream
)/
=======
)/ 
>>>>>>> Stashed changes
'''

[tool.isort]
profile = "black"
known_first_party = ["backend"]
line_length = 88
skip = [
    "venv",
    ".env",
    "build",
    "dist",
    "manage.py",
    "migrations"
]
<<<<<<< Updated upstream
=======
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
>>>>>>> Stashed changes

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = '''
/(
    migrations
  | venv
  | \.env
  | build
  | dist
  | manage\.py
<<<<<<< Updated upstream
)/
=======
)/ 
>>>>>>> Stashed changes
'''

[tool.django-stubs]
django_settings_module = "project.settings"
