# Generated by Django 5.1.7 on 2025-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="audiofile",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="audio_files", to="audio.tag"
            ),
        ),
    ]
