# Generated by Django 5.1.7 on 2025-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0003_tag_audiofile_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
