// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/6/2025, 6:15:25 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/jakub/projects/emplocity-audio-upload-thing/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/plugins/**/*.{js,ts,mjs}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/composables/**/*.{js,ts,mjs}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/utils/**/*.{js,ts,mjs}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/jakub/projects/emplocity-audio-upload-thing/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;