# Generated by Django 5.1.7 on 2025-06-03 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ext_order_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "payu_order_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="PLN", max_length=3)),
                ("description", models.CharField(max_length=255)),
                (
                    "buyer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "buyer_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "redirect_uri_payu",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Order",
                "verbose_name_plural": "Payment Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
